#include "XYZWriter.h"
#include "utils/CLIUtils.h"
#include <filesystem>
#include <iomanip>
#include <spdlog/spdlog.h>
#include <sstream>

XYZWriter::XYZWriter() { SPDLOG_TRACE("Created new XYZWriter (empty)."); };
XYZWriter::XYZWriter(const std::string &basename) : m_basename{basename} {
    SPDLOG_TRACE("Created new XYZWriter with base name {}", basename);
}
XYZWriter::XYZWriter(const std::string &basename, const std::string &dirname)
    : m_basename{basename}, m_dirname{dirname} {
    SPDLOG_TRACE("Created new XYZWriter with base name {} and directory name {}", basename, dirname);
}
XYZWriter::~XYZWriter() {
    closeFile();
    SPDLOG_TRACE("Destroyed XYZWriter.");
};

void XYZWriter::writeParticles(const ParticleContainer &particles, int iteration) {
    // create output directory in which to store generated XYZ output files
    if (!(std::filesystem::exists(m_dirname))) {
        if (!(std::filesystem::create_directory(m_dirname))) {
            CLIUtils::error("Error creating XYZ directory!", "", false);
        };
    }

    // define file name
    std::stringstream strstr, content;
    strstr << m_dirname << "/" << m_basename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

    openFile(strstr.str());

    // write content to preliminary string stream
    content << particles.size() << std::endl;
    content << "Generated by MolSim 2024-25. See "
               "http://openbabel.org/wiki/XYZ_(format) for "
               "file format documentation."
            << std::endl;

    for (auto &p : particles) {
        std::array<double, 3> x = p.getX();
        content << "Ar ";
        content.setf(std::ios_base::showpoint);

        for (auto &xi : x) {
            content << xi << " ";
        }

        content << std::endl;

        SPDLOG_TRACE("Plotted Particle - {}", p.toString());
    }

    // finalize output
    writeFile(content.str(), strstr.str());
}
