name: Build Documentation

on:
    push:
        branches:
            - "Assignment*"
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up testing dependencies
              run: sudo apt-get update && sudo apt-get install -y cmake doxygen

            - name: Build documentation
              run: mkdir build && cd build && cmake .. && make doc_doxygen
