name: Build Documentation

on:
    push:
        branches:
            - "Assignment*"
            - master
    pull_request:
        branches:
            - master

jobs:
    build-docs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up testing dependencies
              run: sudo apt-get update && sudo apt-get install -y libxerces-c-dev libgtest-dev libspdlog-dev libbenchmark-dev cmake doxygen

            - name: Build documentation
              run: mkdir build && cd build && cmake .. && make doc_doxygen
