name: Check Formatting

on:
    push:
        branches:
            - "Assignment*"
            - master
    pull_request:
        branches:
            - master

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up clang-format
              run: sudo apt-get install -y clang-format

            - name: Run clang-format
              run: |
                  cd scripts && chmod +x format.sh && ./format.sh && cd ..

            - name: Display uncommited changes
              run: |
                  git status && git diff

            - name: Check for uncommitted changes
              run: |
                  if [[ $(git status --porcelain) ]]; then
                      >&2 echo "Code is not formatted. Run clang-format locally or commit the changes."
                      exit 1
                  fi
