name: Run Tests

on:
    push:
        branches:
            - "assignment*"
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up testing dependencies
              run: sudo apt-get update && sudo apt-get install -y build-essential clang clang-format clang-tools clang-tidy cmake libxerces-c-dev

            - name: Build project
              run: mkdir build && cd build && cmake -E env CXXFLAGS="-fsanitize=address" cmake .. && make

            - name: Run tests
              run: cd build/tests && ctest
